### ISSUE TITLE
No matching distribution

### ISSUE THREAD

**Issue by ghost** [thanethomson/python-brewer#1]
Unable to install via pip: sudo -H pip install python-brewer
```
Could not find a version that satisfies the requirement python-brewer (from versions: )
No matching distribution found for python-brewer
```

**Comment by thanethomson** [comment]
This is a super weird one. Checked PyPI now and it seems that somehow, the package was registered, README and all, but none of the package files I uploaded were there (source or wheel distributions).

Apologies for that, I've re-uploaded them and it seems to be working now. See [PyPI](https://pypi.python.org/pypi/python-brewer). If it still gives you trouble, try running:

```bash
> pip --no-cache-dir install python-brewer
```

**Comment by ghost** [comment]
Installed without a hitch, but now `pybrew` fails with the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pybrew", line 7, in <module>
    from pythonbrewer.cmdline import main
  File "/Library/Python/2.7/site-packages/pythonbrewer/__init__.py", line 5, in <module>
    from pythonbrewer.pypi import *
  File "/Library/Python/2.7/site-packages/pythonbrewer/pypi.py", line 9, in <module>
    import html5lib
  File "/Library/Python/2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/Library/Python/2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

Edit: This was solved by `pip install html5lib==1.0b8`

**Comment by thanethomson** [comment]
Thanks for picking that up! What the heck's up with `html5lib`'s versioning scheme? Can't really make head or tail of it 😁  I installed the latest version of it during testing `python-brewer` and it worked fine for me in Python 2.7, 3.5 and 3.6.

Which version of `html5lib` were you using when it gave you the error?

From the [html5lib changelog](https://pypi.python.org/pypi/html5lib), it would appear as though the latest version is `1.0b10` (there have been a number of changes since `1.0b8`). Could you please check for me if `1.0b10` works for you?

**Comment by thanethomson** [comment]
Also, please update to `v0.2.0` of `python-brewer` and let me know if you run into any trouble?

**Comment by thanethomson** [comment]
Closing this issue - seems resolved.

**Comment by ghost** [comment]
Not sure what's going on with `html5lib` since its been about 3 months from their last update.

`pybrew` 0.1.0 worked with `html5lib==1.0b8` but failed with `html5lib==1.0b10` whereas `pybrew` 0.2.0 works with either version (on my machine).

Cool little project you have here. It's been helpful in learning how to port a python project to homebrew.

**Comment by thanethomson** [comment]
Thanks! 👍 😁 Glad `v0.2.0` works.

With regard to `html5lib`'s versioning, it seems as though it uses some kind of dual versioning scheme (0.999999999 seems to correspond to 1.0b10). Super weird...
